name: Build PostgreSQL+Extensions Images

on:
  push:
    branches: [ main, master ]  # ← Triggers on both main/master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [ '15', '16.4', '17' ]
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            PG_VERSION=${{ matrix.pg_version }}
          tags: ghcr.io/${{ github.repository }}:pg${{ matrix.pg_version }}